### ISSUE TITLE
[하이마트] wait 그룹 에이전트는 정책 안받아가도록 수정

### ISSUE THREAD

**Issue by ldcc-daehyunkim** [byunghyun-kang/project-issue#31]
## ■ 고객사
- 하이마트

## ■ 요청기간
- 2022-05-30까지

## ■ 이슈내용
- 초기 구축 당시 생성된 wait 그룹의 정책과 패치된 버전의 정책이 상이하여 에이전트가 정상 동작하지 않음

## ■ 확인내용/재연방법
- 최신 에이전트 설치 후 서버 연결 시, env 파일이 wait 그룹의 env 파일로 변경되어 신규 옵션 누락됨

## ■ 개발내용
- wait 그룹에 속해있는 에이전트는 정책을 안받아가도록 수정 요청

## ■ 참고사항(POS OS / 서버 OS / 윈도우디펜더 및 타보안솔루션 동작 여부 / 이벤트뷰어 등)
-

**Comment by byunghyun-kang** [comment]
2022.05.20 하이마트 서버 적용 완료
- env 파일 생성 시, TOAD_BYPASS_BINS 관련 데이터 임시 하드코딩 고정 처리 (agent, deploy 모듈)
- 추 후, TOAD_BYPASS_BINS 관련 데이터 입력 UI 개발을 통해 개선 예정
